### ISSUE TITLE
suggest using Vader.vim for unit test

### ISSUE THREAD

**Issue by apua** [pi314/ime-phonetic.vim#16]
an example below

![image](https://cloud.githubusercontent.com/assets/829295/24590824/9fa0b97a-1826-11e7-9492-000cfcef79fd.png)

**Comment by pi314** [comment]
WOW, it's cool! I will look into it :D

**Comment by pi314** [comment]
@apua I took a look into [Vader.vim](https://github.com/junegunn/vader.vim), and thought it would be very useful to test user view behavior.
But for now I can't come up with test cases, because this plugin is too premature 😞, the test case above will so not be passed.
I'll keep this in mind, though. If you have idea, feel free to add some!

**Comment by pi314** [comment]
Hey, I read Vader's README again, and found that I missed something: I thought each test case have to be in separated files, but in fact they can be in one file.
I'll think about how to setup a clean environment (venv-like?) to test this plugin (maybe unit test (for methods) first).

**Comment by pi314** [comment]
I think Vader is too verbose to do unit test, and I found another plugin: LucHermitte/vim-UT, which only aims at testing functions results.

**Comment by pi314** [comment]
For the following reasons, I choose Vader.vim (again) for testing:
* I found a little bug in LucHermitte/vim-UT two days ago but the developer doesn't response
* Testing with Vader.vim is not so verbose as I thought
* LucHermitte/vim-UT only aims for testing function results, we need Vader.vim anyway

So this issue is solved with be1f865, feel free to add more test cases.

**Comment by pi314** [comment]
LucHermitte responded :smile:
But Vader.vim is ok now, maybe I'll use LucHermitte/vim-UT in my other repos.
